In [1]:
import pandas as pd
import numpy as np

In [2]:
cols=['latitude','longitude','date','time','crimetype']

In [3]:
lat=np.random.uniform(low=18.4151,high=18.6352,size=10000);lat

array([18.56067713, 18.57852001, 18.52430375, ..., 18.50907566,
       18.47915961, 18.60072172])

In [4]:
long=np.random.uniform(low=73.0447,high=73.9870,size=10000);long

array([73.14370384, 73.56241754, 73.23435   , ..., 73.68554522,
       73.35246004, 73.35168966])

In [43]:
crime=np.random.randint(1,6,10000)

In [44]:
count=np.ones(10000)

In [45]:
def random_date(start, end, position=None):
    start=start.value//10**9
    end=end.value//10**9
    return pd.to_datetime(np.random.randint(start,end,10000),unit='s')
start=pd.to_datetime("2017-01-01")
end=pd.to_datetime("2018-01-01")
ls=random_date(start,end)

In [46]:
df=pd.DataFrame({
    'latitude':lat,
    'longitude':long,
    'data':ls,
    'crime':crime,
    'count':count
})
#1:rape,2:murder,3:dacoity,4:kidnap,5:dowry
df.head()

latitude  longitude                data  crime  count
0  18.560677  73.143704 2017-06-20 21:45:31      4    1.0
1  18.578520  73.562418 2017-05-02 08:50:43      1    1.0
2  18.524304  73.234350 2017-10-11 06:55:53      1    1.0
3  18.465260  73.931716 2017-06-20 05:43:42      4    1.0
4  18.494221  73.880120 2017-08-15 07:34:59      1    1.0

In [47]:
df['crime'].unique()

array([4, 1, 2, 5, 3])

In [48]:
df['date']=df['data'].dt.date

In [49]:
df['time']=df['data'].dt.hour

In [50]:
df.head()

latitude  longitude                data  crime  count        date  time
0  18.560677  73.143704 2017-06-20 21:45:31      4    1.0  2017-06-20    21
1  18.578520  73.562418 2017-05-02 08:50:43      1    1.0  2017-05-02     8
2  18.524304  73.234350 2017-10-11 06:55:53      1    1.0  2017-10-11     6
3  18.465260  73.931716 2017-06-20 05:43:42      4    1.0  2017-06-20     5
4  18.494221  73.880120 2017-08-15 07:34:59      1    1.0  2017-08-15     7

In [51]:
df.drop('data',axis=1,inplace=True)
df.drop('date',axis=1,inplace=True)

In [52]:
df['latitude']=np.floor_divide(df.latitude,0.01)/100

In [53]:
df['longitude']=np.floor_divide(df.longitude,0.01)/100

In [54]:
df.T.to_dict()

{0: {'latitude': 18.56,
  'longitude': 73.14,
  'crime': 4.0,
  'count': 1.0,
  'time': 21.0},
 1: {'latitude': 18.57,
  'longitude': 73.56,
  'crime': 1.0,
  'count': 1.0,
  'time': 8.0},
 2: {'latitude': 18.52,
  'longitude': 73.23,
  'crime': 1.0,
  'count': 1.0,
  'time': 6.0},
 3: {'latitude': 18.46,
  'longitude': 73.93,
  'crime': 4.0,
  'count': 1.0,
  'time': 5.0},
 4: {'latitude': 18.49,
  'longitude': 73.88,
  'crime': 1.0,
  'count': 1.0,
  'time': 7.0},
 5: {'latitude': 18.51,
  'longitude': 73.72,
  'crime': 1.0,
  'count': 1.0,
  'time': 11.0},
 6: {'latitude': 18.59,
  'longitude': 73.89,
  'crime': 2.0,
  'count': 1.0,
  'time': 8.0},
 7: {'latitude': 18.5,
  'longitude': 73.59,
  'crime': 5.0,
  'count': 1.0,
  'time': 21.0},
 8: {'latitude': 18.52,
  'longitude': 73.17,
  'crime': 1.0,
  'count': 1.0,
  'time': 16.0},
 9: {'latitude': 18.56,
  'longitude': 73.58,
  'crime': 3.0,
  'count': 1.0,
  'time': 9.0},
 10: {'latitude': 18.53,
  'longitude': 73.22,
  'crime':

### processing the crime

In [55]:
gdf=df.groupby(['latitude','longitude','time','crime']).count().sort_values(by='count',ascending=False)

In [56]:
gdf

count
latitude longitude time crime       
18.54    73.24     20   4          3
18.44    73.44     0    2          3
18.53    73.41     10   5          3
18.60    73.20     12   1          3
18.53    73.31     5    3          2
18.42    73.27     18   2          2
18.57    73.26     9    2          2
18.55    73.92     5    5          2
18.50    73.27     6    5          2
         73.26     6    5          2
18.59    73.95     23   2          2
18.60    73.51     8    3          2
18.50    73.29     9    3          2
18.46    73.52     4    5          2
18.50    73.23     17   5          2
18.55    73.87     6    4          2
18.42    73.14     22   4          2
18.46    73.56     21   2          2
18.42    73.12     16   3          2
18.52    73.04     1    2          2
18.60    73.08     0    1          2
18.54    73.85     15   3          2
18.45    73.15     0    4          2
18.51    73.82     22   5          2
18.42    73.10     0    4          2
18.54    73.69     23   3          2
18.43    73.65     23   3          2
18.51    73.68     19   5          2
18.56    73.09     2    5          2
18.57    73.11     7    5          2
...                              ...
18.48    73.90     20   3          1
         73.91     4    3          1
                   8    4          1
                   17   2          1
                   18   4          1
                   23   5          1
         73.92     4    4          1
                   6    3          1
                   11   5          1
                   14   5          1
                   18   5          1
         73.90     9    1          1
         73.89     22   1          1
                   9    2          1
         73.88     5    3          1
         73.87     3    2          1
                   7    1          1
                   16   4          1
                   18   5          1
                   20   2          1
         73.88     2    2          1
                   8    2          1
         73.89     8    4          1
         73.88     11   1          1
                   14   5          1
                   17   2          1
                   18   5          1
                   20   3          1
         73.89     0    1          1
18.63    73.98     20   2          1

[9802 rows x 1 columns]

In [57]:
import pyrebase
config = {
    'apiKey': "AIzaSyASZZ_9OlEXA7rQgOyN05OYhjUl9lL5oLM",
    'authDomain': "smartpune-b614c.firebaseapp.com",
    'databaseURL': "https://smartpune-b614c.firebaseio.com",
    'projectId': "smartpune-b614c",
    'storageBucket': "smartpune-b614c.appspot.com",
    'messagingSenderId': "556169280085"
  }

In [58]:
firebase=pyrebase.initialize_app(config)
auth=firebase.auth()

In [ ]:
auth.sign_in_with_email_and_password("rushikesh0203@gmail.com","firebase")

In [ ]:
db=firebase.database()

In [ ]:
db.child('data/crime/').update(df.T.to_dict())